name = "vivo-baru"
main = "worker.js"
compatibility_date = "2024-10-01"

kv_namespaces = [
  { binding = "STORE", id = "a56b029566ee450d9ecd07c8ad529ad2" }
]

[vars]
# Nilai dikirim otomatis dari GitHub Secrets (biarkan kosong)
TG_BOT = ""
TG_CHAT = ""

[env.production]
kv_namespaces = [
  { binding = "STORE", id = "a56b029566ee450d9ecd07c8ad529ad2" }
]
