name = "vivo-baru"
main = "worker.js"
compatibility_date = "2024-10-01"

# ğŸ”‘ Koneksi ke KV Store
kv_namespaces = [
  { binding = "STORE", id = "a56b029566ee450d9ecd07c8ad529ad2" }
]

# ğŸ”” Variabel Telegram (diisi otomatis dari GitHub Secrets)
[vars]
TG_BOT_TOKEN = ""
TG_CHAT_ID   = ""

# â±ï¸ Cronjob: jalan tiap 15 menit
[triggers]
crons = ["*/15 * * * *"]

# ğŸŒ Environment production
[env.production]
kv_namespaces = [
  { binding = "STORE", id = "a56b029566ee450d9ecd07c8ad529ad2" }
]
